baseURL = 'https://clustersandclimate.com/' # <- Your blog's base URL
languageCode = 'en-us'
title = 'Clusters and Climate'
theme = 'pehtheme'

summaryLength = '20' # <- 20 words are approximately 160 characters

# Analytics Configuration (choose one)
googleAnalytics = 'G-W43KWS3B37' # <- Your Google Analytics 4 measurement ID

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'When not debugging clusters or decoding currents, I wander the wild.'
	mainSections = ['climate', 'diary', 'life','outdoor','science','technology'] # <- Main sections of the blog
	defaultContentLanguage = "mr"
	
	# Alternative Analytics Options (uncomment to use)
	# plausibleDomain = 'clustersandclimate.com' # <- For Plausible Analytics
	# simpleAnalytics = true # <- For Simple Analytics
	
[params.author]
	name = 'Dr. Vivek Shilimkar'
	bio = 'Senior Engineer | Climate Scientist | Green Cloud Advocate | Nature Enthusiast | Science Communicator'
	avatar = '/images/vivek-2.jpg'
  	twitter = 'https://x.com/DrViKiShi'
	facebook = 'https://facebook.com/vivekshilimkar'
  	instagram = 'https://instagram.com/vi.ki.shi'

[pagination]
	pagerSize = 8 # <- Set the desired number of posts per page 

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Categories'
		pageRef = '/categories'
		weight = 25
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true