apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-ml-demo
  labels:
    app: rancher-ml-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-ml-demo
  template:
    metadata:
      labels:
        app: rancher-ml-demo
    spec:
      containers:
      - name: server
        image: <YOUR_REGISTRY>/rancher-ml-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-ml-demo
spec:
  selector:
    app: rancher-ml-demo
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
